name: Generate Code From Protobuf

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        if: ${{ github.head_ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      - name: Checkout repo
        if: ${{ !github.head_ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install protogen
        run: |
          dotnet tool install --global protobuf-net.Protogen --version 3.0.101

      - name: Install ts-proto
        run: |
          pushd Script
          npm install
          popd

      - name: Generate C# Code
        run: |
          pushd Script
          .\Generate_csharp.ps1
          popd
          
      - name: Generate TS Code
        run: |
          pushd Script
          .\Generate_ts.ps1
          popd

      - name: Commit files
        run: |
          git config --local user.email "411937015@qq.com"
          git config --local user.name "GitHub Action"
          git config --local core.autocrlf input
          git add --all
          git commit -m "Automated ProtoBuf Code Generation" -a --allow-empty
          
      - name: Push changes to github
        uses: ad-m/github-push-action@master
        if: ${{ github.head_ref }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          
      - name: Push changes to github
        uses: ad-m/github-push-action@master
        if: ${{ !github.head_ref }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
